version: 2.1
orbs:
  node: circleci/node@4.1.1
jobs:
  test:
    executor:
      name: node/default
      tag: '14.8.0'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test:ci
          name: Run YARN tests
workflows:
  build_and_test:
    jobs:
      - test